spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/security
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
application:
  security:
    jwt:
      secret-key: AA74BCD0F9B1E58158D9B29C33146F07089FAE346D391AC814A97F160C5D2A68
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
